name: release preview
run-name: npm release preview - ${{ github.ref_name }}

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  preview-release:
    name: Preview npm release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: nix develop --command bash --noprofile --norc -eo pipefail {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
          filter: tree:0
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Preview release
        run: pnpm exec nx release --dry-run --skip-publish
